### ISSUE TITLE
Add installation instruction in the README

### ISSUE THREAD

**Issue by theRealBithive** [advplyr/audiobookshelf-web#10]
Hi, I am not familiar with the Stack; It would be easier to contribute to the documentation if you would add a short section in the README how to run it locally.

**Comment by andrewgdunn** [comment]
I'd second that, came here to see if I could add some more context on how series are supposed to be enumerated.

**Comment by nichwall** [comment]
To set up the development environment, you can run the following commands (on Ubuntu or WSL)

```
sudo apt-get install node npm
git clone git@github.com:advplyr/audiobookshelf-web.git
cd audiobookshelf-web
npm install
npm run dev
```

This will run a local instance of the website which can be accessed at `localhost:3000`, and updates automatically whenever you save the files your working on (so you can run the development server in a separate terminal). To add new guides, you can create a markdown file in `content/`, which will then show up under `localhost:3000/guides/[filename]` if you have the header as shown below (or look at one of the files already existing in `content/`
```
---
title: [insert title here]
slug: [insert name here]
fullpath: /guides/[insert slug here]
---
```

If you're wanting to add images, use the `static/` directory.
