### ISSUE TITLE
Mobile sidebar not showing up

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf-web#28]
When browsing the website on mobile, the sidebar for the guides and documentation is missing. This is not a problem for https://www.audiobookshelf.org/docs because the user can scroll through everything on the same page, but causes problems for https://www.audiobookshelf.org/guides.

Would it be possible to add some sort of hamburger menu (quick googling shows this may be a "flyout menu") to get the list of guides on mobile? 

This issue is mitigated by switching to desktop view in a mobile browser.

**Comment by advplyr** [comment]
Done!

**Comment by nichwall** [comment]
Awesome, it looks great! I did notice it does not work when using a narrow window in my desktop browser (made Firefox window tiny to pretend to be a mobile browser), but the sidebar works correctly in my mobile browser.

**Comment by advplyr** [comment]
Thanks that should be fixed now

**Comment by advplyr** [comment]
Nope it helped, thanks!
