### ISSUE TITLE
New Guide - Setting up local storage on app

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf-web#48]
Guide on how to set up local storage on Android.
Would like some graphics. The guide does not need to be in the same order as below, but should have all of the following:

- [ ] Why to do this (providing files to other apps)
- [ ] Planned features, if applicable (links to notable GH issues)
- [ ] Notable issues, if applicable (links to GH issues)

**Comment by gamendorf** [comment]
Took my first stab at contributing to the project. 
Pull Request: [ Guide- Android Local Storage #68 ](https://github.com/advplyr/audiobookshelf-web/pull/68)

**Comment by nichwall** [comment]
Fixed by #68
