### ISSUE TITLE
iOS Top Bar icons screwed up by the notch

### ISSUE THREAD

**Issue by mdeeter** [advplyr/audiobookshelf-web#55]
iPhone 12 Pro - iOS 17.0.3

![image](https://github.com/advplyr/audiobookshelf-web/assets/136902/3dae34ba-4fd9-49be-b477-b311d9a6f39e)

![image](https://github.com/advplyr/audiobookshelf-web/assets/136902/aa112c21-a949-4eed-aa1e-9ca751e002bf)

**Comment by nichwall** [comment]
This should go in the audiobookshelf repository (which includes the web client).

This is just the audiobookshelf.org website

**Comment by mdeeter** [comment]
oh yeah... sorry... I wasn't paying enough attention... I'll close this and re-create in the app repo

**Comment by mdeeter** [comment]
moved to: https://github.com/advplyr/audiobookshelf-app/issues/939
